document.write('<div id="bottomBar">');
document.write('<div id="bottomContent">');
document.write('<div style="padding-bottom: 10px;"><a href="https://github.com/tigerfarm/tigchat">GitHub project: tfp_____</a></div>');
document.write('<a href="https://twilio.learnupon.com/store">Training</a>');
document.write(' | <a href="https://www.twilio.com/support-plans">Support</a>');
document.write(' | <a href="https://www.twilio.com/company">About Twilio</a>');
document.write('</div>');
document.write('<div style="padding-top: 10px;">2021 Tiger Farm Press</div>');
document.write('</div>');
document.write('<div  style="padding-bottom: 10px;">');
document.write('</div>');
